name: SC_AWAC
device: ${device}
discount: 0.99
reward_scale: 1

actor_lr: 1e-4 
critic_lr: 1e-4
temp_lr: 1e-4
random_eps: 0.3
noise_eps: 0.01
aux_weight: 5
decay: False
action_l2: 1
p_dist: 2
soft_target_tau: 0.005
clip_obs: 200
norm_clip: 5
norm_eps: 0.01
hidden_dim: 256
sampler:
  type: her_seq
  strategy: future
  k: 4
update_epoch: ${update_epoch}

normalize: False
intr_reward: True
raw_env_reward: True

n_action_samples: 1
lam: 1
learnable_temperature: False
init_temperature: 0.001